apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-webclient
  namespace: {{ include "iam.ns" . }}
  labels:
    app: auth-webclient
    {{- include "iam.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webclient.replicas }}
  selector:
    matchLabels:
      app: auth-webclient
  template:
    metadata:
      labels:
        app: auth-webclient
    spec:
      containers:
        - name: web
          image: {{ .Values.webclient.image }}:{{ .Values.webclient.imageTag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef: { name: auth-webclient-config }
            - secretRef:    { name: auth-webclient-secret }
          resources:
{{- merge .Values.resourcesDefaults .Values.webclient.resources | toYaml | nindent 12 }}
          readinessProbe:
            httpGet: { path: /api/health, port: 3000 }
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /api/health, port: 3000 }
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: auth-webclient
  namespace: {{ include "iam.ns" . }}
  labels:
    app: auth-webclient
    {{- include "iam.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: auth-webclient
  ports:
    - name: http
      port: 80
      targetPort: 3000