name: my-secret
namespace:
type: Opaque
stringData:
  # username: admin
  # password: s3cr3t
  # "config.json": |
  #   {
  #     "db": "secret",
  #     "user": "admin",
  #     "password": "s3cr3t"
  #   }
  # "cert.pem": |
  #   -----BEGIN CERTIFICATE-----
  #   MIID...
  #   -----END CERTIFICATE-----
  # "key.pem": |
  #   -----BEGIN PRIVATE KEY-----
  #   MIIE...
  #   -----END PRIVATE KEY-----
